### ISSUE TITLE
Almacenamiento y recuperación de alertas individuales (por candid, oid) para stamps service

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/batch_processing#14]
```[tasklist]
### Tasks
- [ ] Actualizar S3 step para seguir nuevo almacenamiento de parquet
- [ ] Crear tabla de mapeo candid, oid a parquet
- [ ] Actualizar stamps service para leer desde parquet las stamps
```

**Comment by dirodriguezm** [comment]
Documento Notion con documentación: https://www.notion.so/alerce/Raw-storage-batch-process-d4a8cbfb6cac46a7a5193c12912da374?pvs=4
