### ISSUE TITLE
Reprocesamiento 6 de diciembre

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/batch_processing#8]
```[tasklist]
### Tasks
- [ ] Estimar cantidad de alertas por reprocesar desde el 6 de diciembre
- [ ] Estimar factibilidad de ejecución en EMR (cantidad de máquinas, recursos, etc) [opcional]
- [ ] Dado X recursos y cantidad de alertas, cuánto costaría hacer el reprocesamiento
```

**Comment by dirodriguezm** [comment]
- tiempos de ejecución por paso en https://grafana.alerce.online -> pipeline alerts
- tiempo de pipeline por alerta en el paper: https://ui.adsabs.harvard.edu/abs/2021AJ....161..242F/abstract
